#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
app_product_show:
    path: '/product/{id}'
    controller: 'App\Controller\ProductController::show'
    requirements:
        id: '\d+' # Contrainte pour que l'ID soit un entier
    methods: ['GET']


